services:
  - type: web
    name: mangodesk-api
    env: node
    buildCommand: npm install; npm install marked
    startCommand: node index.js
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
